services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./scripts/insertScript.sql:/docker-entrypoint-initdb.d/insertScript.sql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      MAIL_SECRET: ${MAIL_SECRET}
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - /c/Users/ALVARO/OneDrive/Documentos/animal-shelter/backend/uploads:/uploads


#  frontend:
#    build: ./frontend
#    depends_on:
#      - backend
#    ports:
#      - "${FRONTEND_PORT}:80"

volumes:
  mysql_data:
